version: '3.8'

services:
  backend:
    build: ./backend
    container_name: stroke-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    networks:
      - stroke-network

  frontend:
    build: ./frontend
    container_name: stroke-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - stroke-network

networks:
  stroke-network:
    driver: bridge