version: '3.8'

services:
  backend:
    image: yashelke/stroke-backend:1.0
    container_name: stroke-backend-prod
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: always
    networks:
      - stroke-network

  frontend:
    image: yashelke/stroke-frontend:1.0
    container_name: stroke-frontend-prod
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
    networks:
      - stroke-network

networks:
  stroke-network:
    driver: bridge